### ISSUE TITLE
FC051 tries to validate temp files of the editors

### ISSUE THREAD

**Issue by tmatilai** [acrmp/foodcritic#172]
While testing Foodcritic v3.0.0 I suddenly started getting "invalid byte sequence in UTF-8" error from Erubis. It seems that [FC051](http://www.foodcritic.io/#FC051) (Template partials loop indefinitely) is going through Vim swap files which contain binary data. The full stack trace can be found in [this gist](https://gist.github.com/tmatilai/814375a891fb0039c636).

I don't know what would be a good way to include only text templates. Restrict the glob to `**/*.erb` is maybe too strict. And validating only templates referenced in recipes might still leave something out.

**Comment by miketheman** [comment]
I can confirm that this is still indeed a problem - I have an ERB template file with a Unicode character that bombs on foodcritic.

**Comment by gsaslis** [comment]
same here guys... Can this really not point the blame on a specific file that's causing the problem?

**Comment by nukepuppy** [comment]
same story - no idea what this mystery file could be at this moment

**Comment by gsaslis** [comment]
hi guys! thanks for the fix @odcinek ! 

Anyone have any clue when this will be due for release? Noticed it's just left to 'Unreleased' in the CHANGELOG.md

**Comment by spuder** [comment]
I ran into the same problem, workaround

    find foobar -name ".DS_Store" -exec rm {} \;

Is there a way to ignore specific files with foodcritic?

**Comment by miketheman** [comment]
Support https://github.com/acrmp/foodcritic/issues/318 !

**Comment by gsaslis** [comment]
@spuder yeah i'd ended up doing the exact same thing... : )  eventually, I just stopped using foodcritic till this was resolved. 

will now be waiting for the 5.0 release!  ; )

**Comment by howardabrams** [comment]
I am seeing the same problem even when I run `foodcritic` with a particular file that I'm sure doesn't have any UTF-8 characters in it (in fact, this fails for everything that I check):

     $ file -I recipes/default.rb
     recipes/default.rb: text/plain; charset=us-ascii   

     $ foodcritic recipes/default.rb
     /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/erubis-2.7.0/lib/erubis/converter.rb:132:in `scan': invalid byte sequence in UTF-8 (ArgumentError)
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/erubis-2.7.0/lib/erubis/converter.rb:132:in `convert_input'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/erubis-2.7.0/lib/erubis/converter.rb:36:in `convert'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/template.rb:13:in `extract'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/api.rb:553:in `template_expressions_only'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/api.rb:494:in `uncached_read_ast'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/api.rb:225:in `read_ast'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/api.rb:349:in `templates_included'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/rules.rb:734:in `block (4 levels) in load'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/rules.rb:732:in `select'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/rules.rb:732:in `block (3 levels) in load'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:241:in `yield'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:241:in `matches'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:97:in `cookbook_matches'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:75:in `block (2 levels) in check'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:64:in `each'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:64:in `block in check'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:56:in `each'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:56:in `check'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:26:in `check'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/bin/foodcritic:5:in `<module:FoodCritic>'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/gems/foodcritic-4.0.0/bin/foodcritic:3:in `<top (required)>'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/bin/foodcritic:23:in `load'
         from /Users/howard.abrams/.rvm/gems/ruby-1.9.3-p484@wpc/bin/foodcritic:23:in `<main>'

**Comment by nickma** [comment]
Still not sure what it was but doing file -I *.erb in templates folder showed some text/x-php; charset=unknown-8bit , after fixing the encoding it all worked again . Foodcritic and berks upload are no longer complaining.
